language: rust
cache:
    directories:
        - $HOME/.cargo
rust:
    - 1.6.0
    - stable
    - beta
    - nightly
os:
    - linux
    - osx
env:
  global:
    - secure: kd+Q+IWrHUZK+BwwEh37IiR7B76yyvfjAB3Gx6roshKyAk2KmduoyLGv6v902gbLAtt/8JtPMBHZdKbMv7A1eKBsCOF/rMz1rHziuTbnFwfnx6UN+jalZZRIYmn20M7I1UfvhcvWXqvcrpo84NbhOYlXMmvI+X6HZ2rSIsYta6E=
    - VERBOSE: 1
  matrix:
    - PNET_FEATURES="travis with-syntex" PNET_MACROS_FEATURES="travis with-syntex"
    - PNET_FEATURES="travis nightly clippy" PNET_MACROS_FEATURES="travis clippy"
    - PNET_FEATURES="travis nightly" PNET_MACROS_FEATURES="travis"
matrix:
  allow_failures:
    - rust: nightly
  exclude:
    - rust: 1.6.0
      env: PNET_FEATURES="travis nightly clippy" PNET_MACROS_FEATURES="travis clippy"
    - rust: 1.6.0
      env: PNET_FEATURES="travis nightly" PNET_MACROS_FEATURES="travis"
    - rust: stable
      env: PNET_FEATURES="travis nightly clippy" PNET_MACROS_FEATURES="travis clippy"
    - rust: stable
      env: PNET_FEATURES="travis nightly" PNET_MACROS_FEATURES="travis"
    - rust: beta
      env: PNET_FEATURES="travis nightly clippy" PNET_MACROS_FEATURES="travis clippy"
    - rust: beta
      env: PNET_FEATURES="travis nightly" PNET_MACROS_FEATURES="travis"
script:
    - make travis_script
notifications:
    irc:
        channels:
            - "chat.freenode.net#libpnet"
        use_notice: true
