[package]
name = "pnet"
version = "0.9.0"
authors = [ "Robert Clipsham <robert@octarineparrot.com>" ]
license = "MIT/Apache-2.0"
homepage = "https://github.com/libpnet/libpnet"
repository = "https://github.com/libpnet/libpnet"
documentation = "http://octarineparrot.com/assets/libpnet/doc/pnet/"
description = "Cross-platform, low level networking using the Rust programming language."
readme = "README.md"
keywords = ["networking", "transport", "datalink", "packet", "protocol"]
build = "build.rs"

[lib]
name = "pnet"

[features]
default = ["with-syntex"]
nightly = ["pnet_macros_plugin"]
netmap = ["netmap_sys"]
appveyor = []
travis = []
with-syntex = ["syntex", "pnet_macros/with-syntex"]

[dependencies.clippy]
optional = true
version = ">=0.0"

[dependencies.netmap_sys]
features = ["netmap_with_libs"]
optional = true
version = ">=0.0"

[dependencies.libc]
version = "=0.1.12"

[dependencies.syntex]
version = "0.31.*"
optional = true

[dependencies.pnet_macros]
optional = true
default-features = false
features = []
path = "pnet_macros"
version = ">=0.8"

[dependencies.pnet_macros_plugin]
optional = true
path = "pnet_macros_plugin"
version = ">=0.1"

[dependencies.pnet_macros_support]
path = "pnet_macros_support"
version = ">=0.1"

[dev-dependencies]
time = ">=0.1"

[build-dependencies]
syntex = { version = "0.31.*", optional = true }
pnet_macros = { path = "pnet_macros", version = ">=0.6" }
