[package]
name = "pnet_macros"
version = "0.21.0"
authors = ["Robert Clipsham <robert@octarineparrot.com>"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/libpnet/libpnet"
repository = "https://github.com/libpnet/libpnet"
description = "Automatic bit manipulation for binary data formats"
readme = "../README.md"
keywords = ["networking", "bitfields", "packet", "protocol"]
categories = ["network-programming", "parsing"]

[features]
default = []
travis = []

[dev-dependencies]
pnet_base = { path = "../pnet_base", version = "0.21.0" }
pnet_macros_support = { path = "../pnet_macros_support", version = "0.21.0" }

[dependencies]
regex = "0.2.*"
syntex = "0.42"
syntex_syntax = "0.42"
