[package]

name = "pnet_macros"
version = "0.0.1"
authors = ["Robert Clipsham <robert@octarineparrot.com>"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/libpnet/libpnet"
repository = "https://github.com/libpnet/libpnet"
documentation = "http://octarineparrot.com/assets/libpnet/doc/pnet/"
description = "Macros for libpnet"
readme = "../README.md"
keywords = ["networking", "transport", "datalink", "packet", "protocol"]

[lib]
name = "pnet_macros"
plugin = true

[dev-dependencies.pnet]
path = ".."
version = "*"

[dependencies]
regex = "*"
