[package]
name = "pnet_macros"
version = "0.13.1"
authors = ["Robert Clipsham <robert@octarineparrot.com>"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/libpnet/libpnet"
repository = "https://github.com/libpnet/libpnet"
documentation = "http://octarineparrot.com/assets/libpnet/doc/pnet/"
description = "Automatic bit manipulation for binary data formats"
readme = "../README.md"
keywords = ["networking", "bitfields", "packet", "protocol"]

[lib]
name = "pnet_macros"

[features]
default = []
travis = []
with-syntex = ["syntex", "syntex_syntax"]

[dev-dependencies]
compiletest_rs = ">=0.0"

[dev-dependencies.pnet]
default-features = false
features = ["nightly"]
path = ".."
version = ">=0.9"

[dev-dependencies.pnet_macros_plugin]
path = "../pnet_macros_plugin"
version = ">=0.1"

[dev-dependencies.pnet_macros_support]
path = "../pnet_macros_support"
version = ">=0.1"

[dependencies]
regex = "0.2.*"
syntex = { version = "0.42.*", optional = true }
syntex_syntax = { version = "0.42.*", optional = true }

[dependencies.clippy]
optional = true
version = ">=0.0"
