[package]
name = "pnet_sys"
version = "0.20.0"
authors = ["Robert Clipsham <robert@octarineparrot.com>", "Linus FÃ¤rnstrand <faern@faern.net>"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/libpnet/libpnet"
repository = "https://github.com/libpnet/libpnet"
description = "Access to network related system function and calls."
keywords = ["networking", "datalink", "ethernet", "raw"]
categories = ["network-programming"]

[dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = "0.2"
ws2_32-sys = "0.2"
